"""strutura do bd

Revision ID: ed3757624dac
Revises: 
Create Date: 2022-11-13 21:55:34.318453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3757624dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('marca', sa.String(length=64), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suplementos_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_suplementos_preco'), ['preco'], unique=False)
        batch_op.create_index(batch_op.f('ix_suplementos_product_name'), ['product_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suplementos_product_name'))
        batch_op.drop_index(batch_op.f('ix_suplementos_preco'))
        batch_op.drop_index(batch_op.f('ix_suplementos_marca'))

    op.drop_table('suplementos')
    # ### end Alembic commands ###
